Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -87,9 +87,21 @@ jobs:
           echo "RUN_NUMBER=$RUN_NUMBER"
           echo "REPOSITORY=$REPOSITORY"
 
-          # Build and push the new latest image
+          # Build the new latest image
           docker build -t $ECR_REGISTRY/$REPOSITORY:latest .
+          
+          # Push the new latest image
           docker push $ECR_REGISTRY/$REPOSITORY:latest
+          
+          # Check if the image is available before tagging and pushing with the run number
+          if docker pull $ECR_REGISTRY/$REPOSITORY:latest; then
+            # Tag and push the new latest image with the run number
+            docker tag $ECR_REGISTRY/$REPOSITORY:latest $ECR_REGISTRY/$REPOSITORY:$RUN_NUMBER
+            docker push $ECR_REGISTRY/$REPOSITORY:$RUN_NUMBER
+          else
+            echo "Failed to pull the latest image. Aborting tagging and pushing with the run number."
+            exit 1
+          fi
 
 
 
