Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -56,23 +56,38 @@ jobs:
         with:
           mask-password: 'true'
 
+      - name: Check run number
+        id: check-run-number
+        run: echo "GITHUB_RUN_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
+
       - name: Build, tag, and push image to Amazon ECR
         id: build-image
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          COMMIT_SHA: ${{ github.run_number }}
+          RUN_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
           REPOSITORY: autotask-stripe
         run: |
+          echo "ECR_REGISTRY=$ECR_REGISTRY"
+          echo "RUN_NUMBER=$RUN_NUMBER"
+          echo "REPOSITORY=$REPOSITORY"
+          
+          # Ensure the run number is not empty
+          if [ -z "$RUN_NUMBER" ]; then
+            echo "Error: RUN_NUMBER is empty"
+            exit 1
+          fi
+          
           # Build a docker container and push it to ECR 
           docker build -t $ECR_REGISTRY/$REPOSITORY:$RUN_NUMBER .
           docker push $ECR_REGISTRY/$REPOSITORY:$RUN_NUMBER
 
           # Check if 'latest' tag exists and is immutable before tagging
-          if ! aws ecr describe-images --repository-name $REPOSITORY --image-ids imageTag=latest 2>&1 | grep -q "Image not found"; then
+          if aws ecr describe-images --repository-name $REPOSITORY --image-ids imageTag=latest 2>&1 | grep -q "Image already exists"; then
             echo "'latest' tag already exists and cannot be overwritten."
           else
             # Tag the image as 'latest' if it doesn't already exist
             docker tag $ECR_REGISTRY/$REPOSITORY:$RUN_NUMBER $ECR_REGISTRY/$REPOSITORY:latest
             docker push $ECR_REGISTRY/$REPOSITORY:latest
           fi
+
           
