Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -60,10 +60,19 @@ jobs:
         id: build-image
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          COMMIT_SHA: ${{ github.sha }}
+          COMMIT_SHA: ${{ github.run_number }}
           REPOSITORY: autotask-stripe
         run: |
           # Build a docker container and push it to ECR 
-          docker build -t $ECR_REGISTRY/$REPOSITORY:$COMMIT_SHA .
-          docker push $ECR_REGISTRY/$REPOSITORY:$COMMIT_SHA
+          docker build -t $ECR_REGISTRY/$REPOSITORY:$RUN_NUMBER .
+          docker push $ECR_REGISTRY/$REPOSITORY:$RUN_NUMBER
+
+          # Check if 'latest' tag exists and is immutable before tagging
+          if ! aws ecr describe-images --repository-name $REPOSITORY --image-ids imageTag=latest 2>&1 | grep -q "Image not found"; then
+            echo "'latest' tag already exists and cannot be overwritten."
+          else
+            # Tag the image as 'latest' if it doesn't already exist
+            docker tag $ECR_REGISTRY/$REPOSITORY:$RUN_NUMBER $ECR_REGISTRY/$REPOSITORY:latest
+            docker push $ECR_REGISTRY/$REPOSITORY:latest
+          fi
           
